import os                       # Used to create directories
import time                     # Used to time how long the script takes to run
import numpy as np              # Used for numerical operations and random sampling
import pandas as pd             # Used to organize the final data and save it as a CSV
import matplotlib.pyplot as plt # Used to generate plots of the dataset
import seaborn as sns           # Used for advanced EDA plotting
from scipy.integrate import solve_ivp  # The ODE solver that calculates the reactor's behavior
from concurrent.futures import ProcessPoolExecutor # Used to parallelize the code across CPU cores
import multiprocessing          # Used to count the number of CPU cores available

# =============================================================================
# 1. BASE CONSTANTS (Fixed physical properties of the system)
# These represent the specific chemical and physical traits of the reactor.
# =============================================================================
Ea  = 72750     # Activation energy (J/gmol): Energy required to start the reaction
R   = 8.314     # Ideal gas constant (J/gmol/K)
k0  = 7.2e10    # Arrhenius rate constant (1/min): Pre-exponential factor for the reaction rate
V   = 100.0     # Reactor Volume (L)
rho = 1000.0    # Density of the fluid (g/L)
Cp  = 0.239     # Heat capacity (J/g/K): How much energy is needed to heat the fluid
dHr = -5.0e4    # Enthalpy of reaction (J/mol): Heat released by the exothermic reaction
UA  = 5.0e4     # Heat transfer coefficient (J/min/K): How well the cooling jacket removes heat

# =============================================================================
# 2. MATHEMATICAL MODEL (The differential equations)
# =============================================================================

def k(T):
    """
    Calculates the reaction rate constant based on the current temperature.
    This uses the Arrhenius equation: k = k0 * exp(-Ea / (R * T))
    """
    return k0 * np.exp(-Ea / (R * T))

def deriv(t, y, q, cAi, Ti, Tc):
    """
    This function defines the system of Ordinary Differential Equations (ODEs).
    It tells the solver how the concentration (cA) and temperature (T) change at any given moment 't'.
    """
    # Unpack the current state variables
    cA, T = y
    
    # Differential Equation 1: Mass Balance (Change in concentration over time)
    # (Flow In - Flow Out) - (Amount consumed by the reaction)
    dcAdt = (q/V)*(cAi - cA) - k(T)*cA
    
    # Differential Equation 2: Energy Balance (Change in temperature over time)
    # (Heat from fluid flowing in/out) + (Heat generated by reaction) - (Heat removed by coolant)
    dTdt = (q/V)*(Ti - T) + (-dHr/rho/Cp)*k(T)*cA + (UA/V/rho/Cp)*(Tc-T)
    
    # Return the rates of change to the solver
    return [dcAdt, dTdt]

# =============================================================================
# 3. WORKER FUNCTION (Executes a single simulation run)
# =============================================================================

def run_simulation(params):
    """
    Takes a single combination of parameters, runs the ODE solver for 10 minutes,
    and returns the initial inputs alongside the final resulting outputs.
    """
    # Unpack the specific parameters for this run
    q_curr, cAi_curr, Ti_curr, Tc_curr = params
    
    # Define the time window for the simulation (0 to 10 minutes)
    t_initial = 0.0
    t_final = 10.0
    
    # Define the initial starting state of the reactor at t=0
    cA0 = 0.5       # Starting concentration (mol/L)
    T0 = 350.0      # Starting temperature (K)
    
    # Run the initial value problem (IVP) solver
    # We pass the 'deriv' function, the time span, the initial conditions, and our varied arguments
    soln = solve_ivp(
        deriv, 
        [t_initial, t_final], 
        [cA0, T0], 
        args=(q_curr, cAi_curr, Ti_curr, Tc_curr)
    )
    
    # Return a dictionary containing the inputs used and the final targets at t=10
    # soln.y[0][-1] gets the very last value of the concentration array
    # soln.y[1][-1] gets the very last value of the temperature array
    return {
        "q_input": q_curr,
        "cAi_input": cAi_curr,
        "Ti_input": Ti_curr,
        "Tc_input": Tc_curr,
        "final_cA": soln.y[0][-1],
        "final_T": soln.y[1][-1]
    }

# =============================================================================
# 4. MAIN EXECUTION & MULTIPROCESSING
# =============================================================================

# The "if __name__ == '__main__':" block is required by Python when using multiprocessing.
# It prevents background worker processes from accidentally running the entire script from the top again.
if __name__ == '__main__':
    n_samples = 21000 # Total number of data points to generate
    
    # Generate arrays of random inputs (Features) using a uniform distribution
    np.random.seed(42) # Set a seed so the random numbers are reproducible
    q_samples = np.random.uniform(80.0, 120.0, n_samples)      
    cAi_samples = np.random.uniform(0.8, 1.2, n_samples)       
    Ti_samples = np.random.uniform(330.0, 370.0, n_samples)    
    Tc_samples = np.random.uniform(290.0, 310.0, n_samples)    
    
    # Combine the separate arrays into a single list of rows (tuples)
    # Each tuple represents one specific configuration for the reactor
    param_list = list(zip(q_samples, cAi_samples, Ti_samples, Tc_samples))
    
    # Count the number of CPU cores available on your machine to maximize speed
    n_cores = multiprocessing.cpu_count()
    print(f"Starting parallel simulation for {n_samples} samples using {n_cores} cores...")
    
    # Start the timer
    start_time = time.time()
    results = [] # Empty list to store the output dictionaries
    
    # Create a pool of worker processes
    with ProcessPoolExecutor(max_workers=n_cores) as executor:
        # executor.map distributes the 'param_list' across the available CPU cores,
        # running 'run_simulation' for each tuple in parallel.
        for i, res in enumerate(executor.map(run_simulation, param_list)):
            results.append(res) # Add the result dictionary to our list
            
            # Print a progress update every 1000 samples
            if (i + 1) % 1000 == 0:
                print(f"Processed {i + 1} samples...")

    # Stop the timer and print the duration
    end_time = time.time()
    print(f"Dataset generation complete in {end_time - start_time:.2f} seconds.")

    # Convert the list of dictionaries into a Pandas DataFrame (like a spreadsheet)
    df = pd.DataFrame(results)
    
    # Create dataset directory if it doesn't exist
    os.makedirs('dataset', exist_ok=True)
    
    # Save the DataFrame to a CSV file on your computer
    df.to_csv("dataset/cstr_21k_dataset_parallel.csv", index=False)
    print("Saved to 'dataset/cstr_21k_dataset_parallel.csv'")

    # =============================================================================
    # 5. DATA VISUALIZATION
    # =============================================================================
    print("Generating plots...")
    
    # Create plots directory if it doesn't exist
    os.makedirs('plots', exist_ok=True)
    
    # Plot 1: Input Distributions
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle('Input Parameter Distributions', fontsize=16)
    
    sns.histplot(df['q_input'], ax=axes[0, 0], color='skyblue', kde=True)
    axes[0, 0].set_title('Flow Rate (q)')
    
    sns.histplot(df['cAi_input'], ax=axes[0, 1], color='lightgreen', kde=True)
    axes[0, 1].set_title('Inlet Concentration (cAi)')
    
    sns.histplot(df['Ti_input'], ax=axes[1, 0], color='salmon', kde=True)
    axes[1, 0].set_title('Inlet Temperature (Ti)')
    
    sns.histplot(df['Tc_input'], ax=axes[1, 1], color='gold', kde=True)
    axes[1, 1].set_title('Coolant Temperature (Tc)')
    
    plt.tight_layout()
    plt.savefig('plots/01_input_distributions.png')
    plt.close()
    
    # Plot 2: Correlation Heatmap
    plt.figure(figsize=(8, 6))
    corr = df.corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm', vmin=-1, vmax=1, fmt=".2f")
    plt.title('Correlation Matrix of CSTR Variables')
    plt.tight_layout()
    plt.savefig('plots/02_correlation_heatmap.png')
    plt.close()
    
    # Plot 3: Safety / Runaway Analysis
    critical_temp = 385.0
    df['status'] = ['Hazard (T > 385K)' if t > critical_temp else 'Normal' for t in df['final_T']]
    
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df, x='Tc_input', y='final_T', hue='status', palette={'Normal': 'teal', 'Hazard (T > 385K)': 'red'}, alpha=0.3, s=15)
    plt.axhline(critical_temp, color='red', linestyle='--', label='Critical Threshold')
    plt.title('Impact of Coolant Temp on Final Temp (Safety Analysis)')
    plt.xlabel('Coolant Temperature Input, Tc (K)')
    plt.ylabel('Final Reactor Temperature (K)')
    plt.legend()
    plt.tight_layout()
    plt.savefig('plots/03_safety_analysis.png')
    
    print("Plots saved to 'plots/' directory:")
    print("- plots/01_input_distributions.png")
    print("- plots/02_correlation_heatmap.png")
    print("- plots/03_safety_analysis.png")
    
    plt.show()